[package]
name = "letterbox"
version = "0.1.0"
edition = "2021"

#[lib]
#name = "letterbox"
#crate-type = ["staticlib", "cdylib"]

[dependencies]
bevy = "0.8.1"
criterion = "0.4.0"
flate2 = "1.0.24"
rand = "0.8.5"
raster = "0.0.7"

[[bench]]
name = "astar_bench"
harness = false
